### ISSUE TITLE
エントリをオープンするメソッドを選択出来る機能に関するドキュメント

### ISSUE THREAD

**Issue by moznion** [moznion/hateblo.vim#18]

**Comment by moznion** [comment]
@boolfool ping ping ping!!!

**Comment by boolfool** [comment]
![みさわ](http://jigokuno.img.jugem.jp/20110519_2117831.gif)

**Comment by moznion** [comment]
![みさわ](http://jigokuno.img.jugem.jp/20090111_795237.gif)
