### ISSUE TITLE
既存記事を開くと、改行コードの判定がおかしいのではないか

### ISSUE THREAD

**Issue by uzulla** [moznion/hateblo.vim#23]
![2013-11-13 3 01 54](https://f.cloud.github.com/assets/870716/1524338/bded407e-4bc4-11e3-9847-c3cae0fd105c.png)
HatebloListから記事をひらくと、このようになります。
なぜか最初の一行だけは、正常(？)にみえます。

環境
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 24 2013 20:45:52)
プラグインなどはすべて20131113 3:05の最新版
GUIでもCUIでも同様

**Comment by moznion** [comment]
はてなブログのウェブUIで編集したエントリはCR+LFになるようです (恐らく)

なのでこちら側でどうするかというと、記事ロード時に一括して末尾の置換をかける位しか思いつかないので
ちょっとその方向でやってみます

**Comment by moznion** [comment]
とりあえず1行目を除外すれば良いのでは無いか、という合意に達したので記すものである

**Comment by moznion** [comment]
1行目落としても駄目でした。
末尾行にCR付いてないいないため正しく検知ができなかった。

ので、全行に対してs/^M$/を行うことで解決しました。
以上メモ。

**Comment by moznion** [comment]
84e301fbb083cd2939cdbcbdea02da219272aaab
及び
8dac443c7ad107c61766cb300e8eff74495ff51f
で解決済みです

**Comment by uzulla** [comment]
仕事とかで、タコがコードをいじった後、CRが大量にでてきたときの気分にならずにすむようになりました、大変精神的です！！！ありがとうございました！！！
